package com.phone.listen.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.phone.listen.bean.CallRecordBean;
import com.phone.listen.bean.TelephoneNumberZone;
import com.phone.listen.bean.WhiteListBean;

import com.phone.listen.greendao.CallRecordBeanDao;
import com.phone.listen.greendao.TelephoneNumberZoneDao;
import com.phone.listen.greendao.WhiteListBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig callRecordBeanDaoConfig;
    private final DaoConfig telephoneNumberZoneDaoConfig;
    private final DaoConfig whiteListBeanDaoConfig;

    private final CallRecordBeanDao callRecordBeanDao;
    private final TelephoneNumberZoneDao telephoneNumberZoneDao;
    private final WhiteListBeanDao whiteListBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        callRecordBeanDaoConfig = daoConfigMap.get(CallRecordBeanDao.class).clone();
        callRecordBeanDaoConfig.initIdentityScope(type);

        telephoneNumberZoneDaoConfig = daoConfigMap.get(TelephoneNumberZoneDao.class).clone();
        telephoneNumberZoneDaoConfig.initIdentityScope(type);

        whiteListBeanDaoConfig = daoConfigMap.get(WhiteListBeanDao.class).clone();
        whiteListBeanDaoConfig.initIdentityScope(type);

        callRecordBeanDao = new CallRecordBeanDao(callRecordBeanDaoConfig, this);
        telephoneNumberZoneDao = new TelephoneNumberZoneDao(telephoneNumberZoneDaoConfig, this);
        whiteListBeanDao = new WhiteListBeanDao(whiteListBeanDaoConfig, this);

        registerDao(CallRecordBean.class, callRecordBeanDao);
        registerDao(TelephoneNumberZone.class, telephoneNumberZoneDao);
        registerDao(WhiteListBean.class, whiteListBeanDao);
    }
    
    public void clear() {
        callRecordBeanDaoConfig.clearIdentityScope();
        telephoneNumberZoneDaoConfig.clearIdentityScope();
        whiteListBeanDaoConfig.clearIdentityScope();
    }

    public CallRecordBeanDao getCallRecordBeanDao() {
        return callRecordBeanDao;
    }

    public TelephoneNumberZoneDao getTelephoneNumberZoneDao() {
        return telephoneNumberZoneDao;
    }

    public WhiteListBeanDao getWhiteListBeanDao() {
        return whiteListBeanDao;
    }

}
