package com.phone.listen.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.phone.listen.bean.TelephoneNumberZone;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "TELEPHONE_NUMBER_ZONE".
*/
public class TelephoneNumberZoneDao extends AbstractDao<TelephoneNumberZone, Long> {

    public static final String TABLENAME = "TELEPHONE_NUMBER_ZONE";

    /**
     * Properties of entity TelephoneNumberZone.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Zone = new Property(1, String.class, "zone", false, "ZONE");
        public final static Property City = new Property(2, String.class, "city", false, "CITY");
    }


    public TelephoneNumberZoneDao(DaoConfig config) {
        super(config);
    }
    
    public TelephoneNumberZoneDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"TELEPHONE_NUMBER_ZONE\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"ZONE\" TEXT," + // 1: zone
                "\"CITY\" TEXT);"); // 2: city
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"TELEPHONE_NUMBER_ZONE\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, TelephoneNumberZone entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String zone = entity.getZone();
        if (zone != null) {
            stmt.bindString(2, zone);
        }
 
        String city = entity.getCity();
        if (city != null) {
            stmt.bindString(3, city);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, TelephoneNumberZone entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String zone = entity.getZone();
        if (zone != null) {
            stmt.bindString(2, zone);
        }
 
        String city = entity.getCity();
        if (city != null) {
            stmt.bindString(3, city);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public TelephoneNumberZone readEntity(Cursor cursor, int offset) {
        TelephoneNumberZone entity = new TelephoneNumberZone( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // zone
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2) // city
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, TelephoneNumberZone entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setZone(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setCity(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(TelephoneNumberZone entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(TelephoneNumberZone entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(TelephoneNumberZone entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
